### ISSUE TITLE
Defer initialization until interaction

### ISSUE THREAD

**Issue by john-golden** [mitydigital/statamic-tinymce-cloud#13]
### Bug description

It it possible to defer the initialization of the TinyMCE instances until a user interacts with the editor? If there are multiple instances on pages using replicator sets the usage limit is quickly reached.

### Steps to reproduce

Use the TinyMCE field in a multiple instances per page.

### Environment and versions

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.8.0
PHP Version: 8.2.12
Composer Version: 2.6.3
Environment: staging
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: mailgun
Queue: sync
Session: file

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.6.1 PRO

Statamic Addons
mitydigital/feedamic: 2.3.3
mitydigital/statamic-tinymce-cloud: 3.0.0
rias/statamic-data-import: 1.5.0
statamic/seo-pro: 6.0.3
teamnovu/statamic-images-missing-alt: 1.0.4
```
