### ISSUE TITLE
The Tiny Cloud config file could not be found. Make sure you have at least one configuration saved

### ISSUE THREAD

**Issue by Pickle99** [mitydigital/statamic-tinymce-cloud#9]
### Bug description

On dev environment im getting this error, however its not presented on localhost (i had this error on localhost, however i fixed it when i added second configuration file, i did the same on server, but im still getting this pop-up error everytime i enter the page with tinymce field)

### Steps to reproduce

I tired to remove configuration files and re-create them again, change configuration files for fieldset and etc, on server it still doesnt help. On localhost it got fixed after that.

Full Editor configuration file:
{
     "height": 500,
     "menubar": false,
     "plugins": ["image", "table", "wordcount"],
     "toolbar": "undo redo | bold italic backcolor | alignleft aligncenter alignright | bullist numlist | image | table | help"
}

Simple Editor configuration file:
{
     "height": 200,
     "menubar": false,
     "plugins": [],
     "toolbar": "undo redo | bold italic backcolor | help"
}

### Environment and versions

```yaml
Environment
Application Name: Redberry
Laravel Version: 10.23.1
PHP Version: 8.1.12-1ubuntu4.3
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: localhost:8000
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 9
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.21.0 PRO

Statamic Addons
aerni/font-awesome: 2.0.0
goldnead/statamic-toc: 1.4
jezzdk/statamic-wp-import: 1.6.0
mitydigital/statamic-tinymce-cloud: 2.1.2
ndx/statamic-bard-color-picker: 1.2.0
statamic/collaboration: 0.7.2
statamic/eloquent-driver: 2.7.0
statamic/seo-pro: 5.2.2
visuellverstehen/statamic-classify: 2.6.1

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Taxonomies: eloquent
Terms: eloquent
```
